services:
  catalogdb:
    image: postgres
  orderdb:
    image: postgres
  chatdb:
    image: postgres
  keycloak:
    image: quay.io/keycloak/keycloak:26.1.4
  keycloakdb:
    image: postgres
    


volumes:
  postgres_catalog:
  postgres_keycloak:
  postgres_order:
  postgres_chat:
